// Code generated by tools/codegen/genai. DO NOT EDIT.
// Source: libs/genai/0.11.0/include/ort_genai_c.h

package api

// Opaque pointer types for ONNX Runtime GenAI C API
type OgaResult uintptr
type OgaGeneratorParams uintptr
type OgaGenerator uintptr
type OgaRuntimeSettings uintptr
type OgaConfig uintptr
type OgaModel uintptr
type OgaSequences uintptr
type OgaTokenizer uintptr
type OgaTokenizerStream uintptr
type OgaTensor uintptr
type OgaImages uintptr
type OgaNamedTensors uintptr
type OgaMultiModalProcessor uintptr
type OgaAudios uintptr
type OgaStringArray uintptr
type OgaAdapters uintptr
type OgaEngine uintptr
type OgaRequest uintptr
