// Code generated by tools/codegen/genai. DO NOT EDIT.
// Source: libs/genai/0.11.0/include/ort_genai_c.h

package api

import (
	"github.com/ebitengine/purego"
)

// Funcs contains function pointers to ONNX Runtime GenAI C API functions.
type Funcs struct {
	Shutdown                                            func()
	ResultGetError                                      func(OgaResult) *byte
	SetLogBool                                          func(*byte, bool) OgaResult
	SetLogString                                        func(*byte, *byte) OgaResult
	DestroyResult                                       func(OgaResult)
	DestroyString                                       func(*byte)
	DestroyNamedTensors                                 func(OgaNamedTensors)
	CreateSequences                                     func(*OgaSequences) OgaResult
	DestroySequences                                    func(OgaSequences)
	SequencesCount                                      func(OgaSequences) uintptr
	AppendTokenSequence                                 func(*int32, uintptr, OgaSequences) OgaResult
	AppendTokenToSequence                               func(int32, OgaSequences, uintptr) OgaResult
	SequencesGetSequenceCount                           func(OgaSequences, uintptr) uintptr
	SequencesGetSequenceData                            func(OgaSequences, uintptr) *int32
	LoadImage                                           func(*byte, *OgaImages) OgaResult
	LoadImages                                          func(OgaStringArray, *OgaImages) OgaResult
	LoadImagesFromBuffers                               func(*uintptr, *uintptr, uintptr, *OgaImages) OgaResult
	DestroyImages                                       func(OgaImages)
	LoadAudio                                           func(*byte, *OgaAudios) OgaResult
	LoadAudios                                          func(OgaStringArray, *OgaAudios) OgaResult
	LoadAudiosFromBuffers                               func(*uintptr, *uintptr, uintptr, *OgaAudios) OgaResult
	DestroyAudios                                       func(OgaAudios)
	CreateRuntimeSettings                               func(*OgaRuntimeSettings) OgaResult
	DestroyRuntimeSettings                              func(OgaRuntimeSettings)
	RuntimeSettingsSetHandle                            func(OgaRuntimeSettings, *byte, uintptr) OgaResult
	CreateConfig                                        func(*byte, *OgaConfig) OgaResult
	ConfigClearProviders                                func(OgaConfig) OgaResult
	ConfigAppendProvider                                func(OgaConfig, *byte) OgaResult
	ConfigSetProviderOption                             func(OgaConfig, *byte, *byte, *byte) OgaResult
	ConfigAddModelData                                  func(OgaConfig, *byte, uintptr, uintptr) OgaResult
	ConfigRemoveModelData                               func(OgaConfig, *byte) OgaResult
	ConfigSetDecoderProviderOptionsHardwareDeviceType   func(OgaConfig, *byte, *byte) OgaResult
	ConfigSetDecoderProviderOptionsHardwareDeviceId     func(OgaConfig, *byte, uint32) OgaResult
	ConfigSetDecoderProviderOptionsHardwareVendorId     func(OgaConfig, *byte, uint32) OgaResult
	ConfigClearDecoderProviderOptionsHardwareDeviceType func(OgaConfig, *byte) OgaResult
	ConfigClearDecoderProviderOptionsHardwareDeviceId   func(OgaConfig, *byte) OgaResult
	ConfigClearDecoderProviderOptionsHardwareVendorId   func(OgaConfig, *byte) OgaResult
	ConfigOverlay                                       func(OgaConfig, *byte) OgaResult
	CreateModel                                         func(*byte, *OgaModel) OgaResult
	CreateModelFromConfig                               func(OgaConfig, *OgaModel) OgaResult
	CreateModelWithRuntimeSettings                      func(*byte, OgaRuntimeSettings, *OgaModel) OgaResult
	ModelGetType                                        func(OgaModel, **byte) OgaResult
	ModelGetDeviceType                                  func(OgaModel, **byte) OgaResult
	DestroyConfig                                       func(OgaConfig)
	DestroyModel                                        func(OgaModel)
	CreateGeneratorParams                               func(OgaModel, *OgaGeneratorParams) OgaResult
	DestroyGeneratorParams                              func(OgaGeneratorParams)
	GeneratorParamsSetSearchNumber                      func(OgaGeneratorParams, *byte, float64) OgaResult
	GeneratorParamsSetSearchBool                        func(OgaGeneratorParams, *byte, bool) OgaResult
	GeneratorParamsTryGraphCaptureWithMaxBatchSize      func(OgaGeneratorParams, int32) OgaResult
	GeneratorParamsSetGuidance                          func(OgaGeneratorParams, *byte, *byte, bool) OgaResult
	CreateGenerator                                     func(OgaModel, OgaGeneratorParams, *OgaGenerator) OgaResult
	DestroyGenerator                                    func(OgaGenerator)
	GeneratorIsDone                                     func(OgaGenerator) bool
	GeneratorIsSessionTerminated                        func(OgaGenerator) bool
	GeneratorSetModelInput                              func(OgaGenerator, *byte, OgaTensor) OgaResult
	GeneratorSetInputs                                  func(OgaGenerator, OgaNamedTensors) OgaResult
	GeneratorAppendTokenSequences                       func(OgaGenerator, OgaSequences) OgaResult
	GeneratorAppendTokens                               func(OgaGenerator, *int32, uintptr) OgaResult
	GeneratorGenerateNextToken                          func(OgaGenerator) OgaResult
	GeneratorGetNextTokens                              func(OgaGenerator, **int32, *uintptr) OgaResult
	GeneratorSetRuntimeOption                           func(OgaGenerator, *byte, *byte) OgaResult
	GeneratorRewindTo                                   func(OgaGenerator, uintptr) OgaResult
	GeneratorGetInput                                   func(OgaGenerator, *byte, *OgaTensor) OgaResult
	GeneratorGetOutput                                  func(OgaGenerator, *byte, *OgaTensor) OgaResult
	GeneratorGetLogits                                  func(OgaGenerator, *OgaTensor) OgaResult
	GeneratorSetLogits                                  func(OgaGenerator, OgaTensor) OgaResult
	GeneratorGetSequenceCount                           func(OgaGenerator, uintptr) uintptr
	GeneratorGetSequenceData                            func(OgaGenerator, uintptr) *int32
	CreateTokenizer                                     func(OgaModel, *OgaTokenizer) OgaResult
	DestroyTokenizer                                    func(OgaTokenizer)
	CreateMultiModalProcessor                           func(OgaModel, *OgaMultiModalProcessor) OgaResult
	DestroyMultiModalProcessor                          func(OgaMultiModalProcessor)
	UpdateTokenizerOptions                              func(OgaTokenizer, **byte, **byte, uintptr) OgaResult
	TokenizerGetBosTokenId                              func(OgaTokenizer, *int32) OgaResult
	TokenizerGetEosTokenIds                             func(OgaTokenizer, **int32, *uintptr) OgaResult
	TokenizerGetPadTokenId                              func(OgaTokenizer, *int32) OgaResult
	TokenizerEncode                                     func(OgaTokenizer, *byte, OgaSequences) OgaResult
	TokenizerEncodeBatch                                func(OgaTokenizer, **byte, uintptr, *OgaTensor) OgaResult
	TokenizerDecodeBatch                                func(OgaTokenizer, OgaTensor, *OgaStringArray) OgaResult
	TokenizerToTokenId                                  func(OgaTokenizer, *byte, *int32) OgaResult
	ProcessorProcessImages                              func(OgaMultiModalProcessor, *byte, OgaImages, *OgaNamedTensors) OgaResult
	ProcessorProcessImagesAndPrompts                    func(OgaMultiModalProcessor, OgaStringArray, OgaImages, *OgaNamedTensors) OgaResult
	ProcessorProcessAudios                              func(OgaMultiModalProcessor, *byte, OgaAudios, *OgaNamedTensors) OgaResult
	ProcessorProcessAudiosAndPrompts                    func(OgaMultiModalProcessor, OgaStringArray, OgaAudios, *OgaNamedTensors) OgaResult
	ProcessorProcessImagesAndAudios                     func(OgaMultiModalProcessor, *byte, OgaImages, OgaAudios, *OgaNamedTensors) OgaResult
	ProcessorProcessImagesAndAudiosAndPrompts           func(OgaMultiModalProcessor, OgaStringArray, OgaImages, OgaAudios, *OgaNamedTensors) OgaResult
	TokenizerDecode                                     func(OgaTokenizer, *int32, uintptr, **byte) OgaResult
	ProcessorDecode                                     func(OgaMultiModalProcessor, *int32, uintptr, **byte) OgaResult
	TokenizerApplyChatTemplate                          func(OgaTokenizer, *byte, *byte, *byte, bool, **byte) OgaResult
	CreateTokenizerStream                               func(OgaTokenizer, *OgaTokenizerStream) OgaResult
	CreateTokenizerStreamFromProcessor                  func(OgaMultiModalProcessor, *OgaTokenizerStream) OgaResult
	DestroyTokenizerStream                              func(OgaTokenizerStream)
	TokenizerStreamDecode                               func(OgaTokenizerStream, int32, **byte) OgaResult
	CreateTensorFromBuffer                              func(uintptr, *int64, uintptr, uintptr, *OgaTensor) OgaResult
	DestroyTensor                                       func(OgaTensor)
	TensorGetType                                       func(OgaTensor, uintptr) OgaResult
	TensorGetShapeRank                                  func(OgaTensor, *uintptr) OgaResult
	TensorGetShape                                      func(OgaTensor, *int64, uintptr) OgaResult
	TensorGetData                                       func(OgaTensor, *uintptr) OgaResult
	CreateNamedTensors                                  func(*OgaNamedTensors) OgaResult
	NamedTensorsGet                                     func(OgaNamedTensors, *byte, *OgaTensor) OgaResult
	NamedTensorsSet                                     func(OgaNamedTensors, *byte, OgaTensor) OgaResult
	NamedTensorsDelete                                  func(OgaNamedTensors, *byte) OgaResult
	NamedTensorsCount                                   func(OgaNamedTensors, *uintptr) OgaResult
	NamedTensorsGetNames                                func(OgaNamedTensors, *OgaStringArray) OgaResult
	SetCurrentGpuDeviceId                               func(int32) OgaResult
	GetCurrentGpuDeviceId                               func(*int32) OgaResult
	CreateStringArray                                   func(*OgaStringArray) OgaResult
	CreateStringArrayFromStrings                        func(**byte, uintptr, *OgaStringArray) OgaResult
	DestroyStringArray                                  func(OgaStringArray)
	StringArrayAddString                                func(OgaStringArray, *byte) OgaResult
	StringArrayGetCount                                 func(OgaStringArray, *uintptr) OgaResult
	StringArrayGetString                                func(OgaStringArray, uintptr, **byte) OgaResult
	CreateAdapters                                      func(OgaModel, *OgaAdapters) OgaResult
	DestroyAdapters                                     func(OgaAdapters)
	LoadAdapter                                         func(OgaAdapters, *byte, *byte) OgaResult
	UnloadAdapter                                       func(OgaAdapters, *byte) OgaResult
	SetActiveAdapter                                    func(OgaGenerator, OgaAdapters, *byte) OgaResult
	CreateEngine                                        func(OgaModel, *OgaEngine) OgaResult
	DestroyEngine                                       func(OgaEngine)
	EngineStep                                          func(OgaEngine, *OgaRequest) OgaResult
	EngineHasPendingRequests                            func(OgaEngine, *bool) OgaResult
	EngineAddRequest                                    func(OgaEngine, OgaRequest) OgaResult
	EngineRemoveRequest                                 func(OgaEngine, OgaRequest) OgaResult
	CreateRequest                                       func(OgaGeneratorParams, *OgaRequest) OgaResult
	RequestAddTokens                                    func(OgaRequest, OgaSequences) OgaResult
	DestroyRequest                                      func(OgaRequest)
	RequestSetOpaqueData                                func(OgaRequest, uintptr) OgaResult
	RequestGetOpaqueData                                func(OgaRequest, *uintptr) OgaResult
	RequestHasUnseenTokens                              func(OgaRequest, *bool) OgaResult
	RequestGetUnseenToken                               func(OgaRequest, *int32) OgaResult
	RequestIsDone                                       func(OgaRequest, *bool) OgaResult
	RegisterExecutionProviderLibrary                    func(*byte, *byte)
	UnregisterExecutionProviderLibrary                  func(*byte)
}

// InitializeFuncs loads all GenAI C API functions from the shared library.
func InitializeFuncs(libraryHandle uintptr) (*Funcs, error) {
	funcs := &Funcs{}
	purego.RegisterLibFunc(&funcs.Shutdown, libraryHandle, "OgaShutdown")
	purego.RegisterLibFunc(&funcs.ResultGetError, libraryHandle, "OgaResultGetError")
	purego.RegisterLibFunc(&funcs.SetLogBool, libraryHandle, "OgaSetLogBool")
	purego.RegisterLibFunc(&funcs.SetLogString, libraryHandle, "OgaSetLogString")
	purego.RegisterLibFunc(&funcs.DestroyResult, libraryHandle, "OgaDestroyResult")
	purego.RegisterLibFunc(&funcs.DestroyString, libraryHandle, "OgaDestroyString")
	purego.RegisterLibFunc(&funcs.DestroyNamedTensors, libraryHandle, "OgaDestroyNamedTensors")
	purego.RegisterLibFunc(&funcs.CreateSequences, libraryHandle, "OgaCreateSequences")
	purego.RegisterLibFunc(&funcs.DestroySequences, libraryHandle, "OgaDestroySequences")
	purego.RegisterLibFunc(&funcs.SequencesCount, libraryHandle, "OgaSequencesCount")
	purego.RegisterLibFunc(&funcs.AppendTokenSequence, libraryHandle, "OgaAppendTokenSequence")
	purego.RegisterLibFunc(&funcs.AppendTokenToSequence, libraryHandle, "OgaAppendTokenToSequence")
	purego.RegisterLibFunc(&funcs.SequencesGetSequenceCount, libraryHandle, "OgaSequencesGetSequenceCount")
	purego.RegisterLibFunc(&funcs.SequencesGetSequenceData, libraryHandle, "OgaSequencesGetSequenceData")
	purego.RegisterLibFunc(&funcs.LoadImage, libraryHandle, "OgaLoadImage")
	purego.RegisterLibFunc(&funcs.LoadImages, libraryHandle, "OgaLoadImages")
	purego.RegisterLibFunc(&funcs.LoadImagesFromBuffers, libraryHandle, "OgaLoadImagesFromBuffers")
	purego.RegisterLibFunc(&funcs.DestroyImages, libraryHandle, "OgaDestroyImages")
	purego.RegisterLibFunc(&funcs.LoadAudio, libraryHandle, "OgaLoadAudio")
	purego.RegisterLibFunc(&funcs.LoadAudios, libraryHandle, "OgaLoadAudios")
	purego.RegisterLibFunc(&funcs.LoadAudiosFromBuffers, libraryHandle, "OgaLoadAudiosFromBuffers")
	purego.RegisterLibFunc(&funcs.DestroyAudios, libraryHandle, "OgaDestroyAudios")
	purego.RegisterLibFunc(&funcs.CreateRuntimeSettings, libraryHandle, "OgaCreateRuntimeSettings")
	purego.RegisterLibFunc(&funcs.DestroyRuntimeSettings, libraryHandle, "OgaDestroyRuntimeSettings")
	purego.RegisterLibFunc(&funcs.RuntimeSettingsSetHandle, libraryHandle, "OgaRuntimeSettingsSetHandle")
	purego.RegisterLibFunc(&funcs.CreateConfig, libraryHandle, "OgaCreateConfig")
	purego.RegisterLibFunc(&funcs.ConfigClearProviders, libraryHandle, "OgaConfigClearProviders")
	purego.RegisterLibFunc(&funcs.ConfigAppendProvider, libraryHandle, "OgaConfigAppendProvider")
	purego.RegisterLibFunc(&funcs.ConfigSetProviderOption, libraryHandle, "OgaConfigSetProviderOption")
	purego.RegisterLibFunc(&funcs.ConfigAddModelData, libraryHandle, "OgaConfigAddModelData")
	purego.RegisterLibFunc(&funcs.ConfigRemoveModelData, libraryHandle, "OgaConfigRemoveModelData")
	purego.RegisterLibFunc(&funcs.ConfigSetDecoderProviderOptionsHardwareDeviceType, libraryHandle, "OgaConfigSetDecoderProviderOptionsHardwareDeviceType")
	purego.RegisterLibFunc(&funcs.ConfigSetDecoderProviderOptionsHardwareDeviceId, libraryHandle, "OgaConfigSetDecoderProviderOptionsHardwareDeviceId")
	purego.RegisterLibFunc(&funcs.ConfigSetDecoderProviderOptionsHardwareVendorId, libraryHandle, "OgaConfigSetDecoderProviderOptionsHardwareVendorId")
	purego.RegisterLibFunc(&funcs.ConfigClearDecoderProviderOptionsHardwareDeviceType, libraryHandle, "OgaConfigClearDecoderProviderOptionsHardwareDeviceType")
	purego.RegisterLibFunc(&funcs.ConfigClearDecoderProviderOptionsHardwareDeviceId, libraryHandle, "OgaConfigClearDecoderProviderOptionsHardwareDeviceId")
	purego.RegisterLibFunc(&funcs.ConfigClearDecoderProviderOptionsHardwareVendorId, libraryHandle, "OgaConfigClearDecoderProviderOptionsHardwareVendorId")
	purego.RegisterLibFunc(&funcs.ConfigOverlay, libraryHandle, "OgaConfigOverlay")
	purego.RegisterLibFunc(&funcs.CreateModel, libraryHandle, "OgaCreateModel")
	purego.RegisterLibFunc(&funcs.CreateModelFromConfig, libraryHandle, "OgaCreateModelFromConfig")
	purego.RegisterLibFunc(&funcs.CreateModelWithRuntimeSettings, libraryHandle, "OgaCreateModelWithRuntimeSettings")
	purego.RegisterLibFunc(&funcs.ModelGetType, libraryHandle, "OgaModelGetType")
	purego.RegisterLibFunc(&funcs.ModelGetDeviceType, libraryHandle, "OgaModelGetDeviceType")
	purego.RegisterLibFunc(&funcs.DestroyConfig, libraryHandle, "OgaDestroyConfig")
	purego.RegisterLibFunc(&funcs.DestroyModel, libraryHandle, "OgaDestroyModel")
	purego.RegisterLibFunc(&funcs.CreateGeneratorParams, libraryHandle, "OgaCreateGeneratorParams")
	purego.RegisterLibFunc(&funcs.DestroyGeneratorParams, libraryHandle, "OgaDestroyGeneratorParams")
	purego.RegisterLibFunc(&funcs.GeneratorParamsSetSearchNumber, libraryHandle, "OgaGeneratorParamsSetSearchNumber")
	purego.RegisterLibFunc(&funcs.GeneratorParamsSetSearchBool, libraryHandle, "OgaGeneratorParamsSetSearchBool")
	purego.RegisterLibFunc(&funcs.GeneratorParamsTryGraphCaptureWithMaxBatchSize, libraryHandle, "OgaGeneratorParamsTryGraphCaptureWithMaxBatchSize")
	purego.RegisterLibFunc(&funcs.GeneratorParamsSetGuidance, libraryHandle, "OgaGeneratorParamsSetGuidance")
	purego.RegisterLibFunc(&funcs.CreateGenerator, libraryHandle, "OgaCreateGenerator")
	purego.RegisterLibFunc(&funcs.DestroyGenerator, libraryHandle, "OgaDestroyGenerator")
	purego.RegisterLibFunc(&funcs.GeneratorIsDone, libraryHandle, "OgaGenerator_IsDone")
	purego.RegisterLibFunc(&funcs.GeneratorIsSessionTerminated, libraryHandle, "OgaGenerator_IsSessionTerminated")
	purego.RegisterLibFunc(&funcs.GeneratorSetModelInput, libraryHandle, "OgaGenerator_SetModelInput")
	purego.RegisterLibFunc(&funcs.GeneratorSetInputs, libraryHandle, "OgaGenerator_SetInputs")
	purego.RegisterLibFunc(&funcs.GeneratorAppendTokenSequences, libraryHandle, "OgaGenerator_AppendTokenSequences")
	purego.RegisterLibFunc(&funcs.GeneratorAppendTokens, libraryHandle, "OgaGenerator_AppendTokens")
	purego.RegisterLibFunc(&funcs.GeneratorGenerateNextToken, libraryHandle, "OgaGenerator_GenerateNextToken")
	purego.RegisterLibFunc(&funcs.GeneratorGetNextTokens, libraryHandle, "OgaGenerator_GetNextTokens")
	purego.RegisterLibFunc(&funcs.GeneratorSetRuntimeOption, libraryHandle, "OgaGenerator_SetRuntimeOption")
	purego.RegisterLibFunc(&funcs.GeneratorRewindTo, libraryHandle, "OgaGenerator_RewindTo")
	purego.RegisterLibFunc(&funcs.GeneratorGetInput, libraryHandle, "OgaGenerator_GetInput")
	purego.RegisterLibFunc(&funcs.GeneratorGetOutput, libraryHandle, "OgaGenerator_GetOutput")
	purego.RegisterLibFunc(&funcs.GeneratorGetLogits, libraryHandle, "OgaGenerator_GetLogits")
	purego.RegisterLibFunc(&funcs.GeneratorSetLogits, libraryHandle, "OgaGenerator_SetLogits")
	purego.RegisterLibFunc(&funcs.GeneratorGetSequenceCount, libraryHandle, "OgaGenerator_GetSequenceCount")
	purego.RegisterLibFunc(&funcs.GeneratorGetSequenceData, libraryHandle, "OgaGenerator_GetSequenceData")
	purego.RegisterLibFunc(&funcs.CreateTokenizer, libraryHandle, "OgaCreateTokenizer")
	purego.RegisterLibFunc(&funcs.DestroyTokenizer, libraryHandle, "OgaDestroyTokenizer")
	purego.RegisterLibFunc(&funcs.CreateMultiModalProcessor, libraryHandle, "OgaCreateMultiModalProcessor")
	purego.RegisterLibFunc(&funcs.DestroyMultiModalProcessor, libraryHandle, "OgaDestroyMultiModalProcessor")
	purego.RegisterLibFunc(&funcs.UpdateTokenizerOptions, libraryHandle, "OgaUpdateTokenizerOptions")
	purego.RegisterLibFunc(&funcs.TokenizerGetBosTokenId, libraryHandle, "OgaTokenizerGetBosTokenId")
	purego.RegisterLibFunc(&funcs.TokenizerGetEosTokenIds, libraryHandle, "OgaTokenizerGetEosTokenIds")
	purego.RegisterLibFunc(&funcs.TokenizerGetPadTokenId, libraryHandle, "OgaTokenizerGetPadTokenId")
	purego.RegisterLibFunc(&funcs.TokenizerEncode, libraryHandle, "OgaTokenizerEncode")
	purego.RegisterLibFunc(&funcs.TokenizerEncodeBatch, libraryHandle, "OgaTokenizerEncodeBatch")
	purego.RegisterLibFunc(&funcs.TokenizerDecodeBatch, libraryHandle, "OgaTokenizerDecodeBatch")
	purego.RegisterLibFunc(&funcs.TokenizerToTokenId, libraryHandle, "OgaTokenizerToTokenId")
	purego.RegisterLibFunc(&funcs.ProcessorProcessImages, libraryHandle, "OgaProcessorProcessImages")
	purego.RegisterLibFunc(&funcs.ProcessorProcessImagesAndPrompts, libraryHandle, "OgaProcessorProcessImagesAndPrompts")
	purego.RegisterLibFunc(&funcs.ProcessorProcessAudios, libraryHandle, "OgaProcessorProcessAudios")
	purego.RegisterLibFunc(&funcs.ProcessorProcessAudiosAndPrompts, libraryHandle, "OgaProcessorProcessAudiosAndPrompts")
	purego.RegisterLibFunc(&funcs.ProcessorProcessImagesAndAudios, libraryHandle, "OgaProcessorProcessImagesAndAudios")
	purego.RegisterLibFunc(&funcs.ProcessorProcessImagesAndAudiosAndPrompts, libraryHandle, "OgaProcessorProcessImagesAndAudiosAndPrompts")
	purego.RegisterLibFunc(&funcs.TokenizerDecode, libraryHandle, "OgaTokenizerDecode")
	purego.RegisterLibFunc(&funcs.ProcessorDecode, libraryHandle, "OgaProcessorDecode")
	purego.RegisterLibFunc(&funcs.TokenizerApplyChatTemplate, libraryHandle, "OgaTokenizerApplyChatTemplate")
	purego.RegisterLibFunc(&funcs.CreateTokenizerStream, libraryHandle, "OgaCreateTokenizerStream")
	purego.RegisterLibFunc(&funcs.CreateTokenizerStreamFromProcessor, libraryHandle, "OgaCreateTokenizerStreamFromProcessor")
	purego.RegisterLibFunc(&funcs.DestroyTokenizerStream, libraryHandle, "OgaDestroyTokenizerStream")
	purego.RegisterLibFunc(&funcs.TokenizerStreamDecode, libraryHandle, "OgaTokenizerStreamDecode")
	purego.RegisterLibFunc(&funcs.CreateTensorFromBuffer, libraryHandle, "OgaCreateTensorFromBuffer")
	purego.RegisterLibFunc(&funcs.DestroyTensor, libraryHandle, "OgaDestroyTensor")
	purego.RegisterLibFunc(&funcs.TensorGetType, libraryHandle, "OgaTensorGetType")
	purego.RegisterLibFunc(&funcs.TensorGetShapeRank, libraryHandle, "OgaTensorGetShapeRank")
	purego.RegisterLibFunc(&funcs.TensorGetShape, libraryHandle, "OgaTensorGetShape")
	purego.RegisterLibFunc(&funcs.TensorGetData, libraryHandle, "OgaTensorGetData")
	purego.RegisterLibFunc(&funcs.CreateNamedTensors, libraryHandle, "OgaCreateNamedTensors")
	purego.RegisterLibFunc(&funcs.NamedTensorsGet, libraryHandle, "OgaNamedTensorsGet")
	purego.RegisterLibFunc(&funcs.NamedTensorsSet, libraryHandle, "OgaNamedTensorsSet")
	purego.RegisterLibFunc(&funcs.NamedTensorsDelete, libraryHandle, "OgaNamedTensorsDelete")
	purego.RegisterLibFunc(&funcs.NamedTensorsCount, libraryHandle, "OgaNamedTensorsCount")
	purego.RegisterLibFunc(&funcs.NamedTensorsGetNames, libraryHandle, "OgaNamedTensorsGetNames")
	purego.RegisterLibFunc(&funcs.SetCurrentGpuDeviceId, libraryHandle, "OgaSetCurrentGpuDeviceId")
	purego.RegisterLibFunc(&funcs.GetCurrentGpuDeviceId, libraryHandle, "OgaGetCurrentGpuDeviceId")
	purego.RegisterLibFunc(&funcs.CreateStringArray, libraryHandle, "OgaCreateStringArray")
	purego.RegisterLibFunc(&funcs.CreateStringArrayFromStrings, libraryHandle, "OgaCreateStringArrayFromStrings")
	purego.RegisterLibFunc(&funcs.DestroyStringArray, libraryHandle, "OgaDestroyStringArray")
	purego.RegisterLibFunc(&funcs.StringArrayAddString, libraryHandle, "OgaStringArrayAddString")
	purego.RegisterLibFunc(&funcs.StringArrayGetCount, libraryHandle, "OgaStringArrayGetCount")
	purego.RegisterLibFunc(&funcs.StringArrayGetString, libraryHandle, "OgaStringArrayGetString")
	purego.RegisterLibFunc(&funcs.CreateAdapters, libraryHandle, "OgaCreateAdapters")
	purego.RegisterLibFunc(&funcs.DestroyAdapters, libraryHandle, "OgaDestroyAdapters")
	purego.RegisterLibFunc(&funcs.LoadAdapter, libraryHandle, "OgaLoadAdapter")
	purego.RegisterLibFunc(&funcs.UnloadAdapter, libraryHandle, "OgaUnloadAdapter")
	purego.RegisterLibFunc(&funcs.SetActiveAdapter, libraryHandle, "OgaSetActiveAdapter")
	purego.RegisterLibFunc(&funcs.CreateEngine, libraryHandle, "OgaCreateEngine")
	purego.RegisterLibFunc(&funcs.DestroyEngine, libraryHandle, "OgaDestroyEngine")
	purego.RegisterLibFunc(&funcs.EngineStep, libraryHandle, "OgaEngineStep")
	purego.RegisterLibFunc(&funcs.EngineHasPendingRequests, libraryHandle, "OgaEngineHasPendingRequests")
	purego.RegisterLibFunc(&funcs.EngineAddRequest, libraryHandle, "OgaEngineAddRequest")
	purego.RegisterLibFunc(&funcs.EngineRemoveRequest, libraryHandle, "OgaEngineRemoveRequest")
	purego.RegisterLibFunc(&funcs.CreateRequest, libraryHandle, "OgaCreateRequest")
	purego.RegisterLibFunc(&funcs.RequestAddTokens, libraryHandle, "OgaRequestAddTokens")
	purego.RegisterLibFunc(&funcs.DestroyRequest, libraryHandle, "OgaDestroyRequest")
	purego.RegisterLibFunc(&funcs.RequestSetOpaqueData, libraryHandle, "OgaRequestSetOpaqueData")
	purego.RegisterLibFunc(&funcs.RequestGetOpaqueData, libraryHandle, "OgaRequestGetOpaqueData")
	purego.RegisterLibFunc(&funcs.RequestHasUnseenTokens, libraryHandle, "OgaRequestHasUnseenTokens")
	purego.RegisterLibFunc(&funcs.RequestGetUnseenToken, libraryHandle, "OgaRequestGetUnseenToken")
	purego.RegisterLibFunc(&funcs.RequestIsDone, libraryHandle, "OgaRequestIsDone")
	purego.RegisterLibFunc(&funcs.RegisterExecutionProviderLibrary, libraryHandle, "OgaRegisterExecutionProviderLibrary")
	purego.RegisterLibFunc(&funcs.UnregisterExecutionProviderLibrary, libraryHandle, "OgaUnregisterExecutionProviderLibrary")

	return funcs, nil
}
